CREATE TABLE `userdetailmaster` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `firstName` varchar(50) DEFAULT NULL,
  `lastName` varchar(50) DEFAULT NULL,
  `joiningDate` datetime DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(50) DEFAULT NULL,
  `lastLogin` datetime DEFAULT NULL,
  `lastLogout` datetime DEFAULT NULL,
  `role` varchar(70) NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `isDeleted` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
);

CREATE TABLE `studentdetailmaster` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `branchId` int(4) DEFAULT NULL,
  `firstName` varchar(50) DEFAULT NULL,
  `lastName` varchar(50) DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `aadhar` decimal(16,0) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `nationality` varchar(10) DEFAULT NULL,
  `registrationNo` decimal(10,0) DEFAULT NULL,
  `regDate` datetime DEFAULT NULL,
  `enrollmentNo` decimal(10,0) DEFAULT NULL,
  `bloodGroup` varchar(10) DEFAULT NULL,
  `admissioDate` datetime DEFAULT NULL,
  `session` varchar(50) DEFAULT NULL,
  `contactNo` decimal(10,0) DEFAULT NULL,
  `caste` varchar(30) DEFAULT NULL,
  `religion` varchar(40) DEFAULT NULL,
  `guardianName` varchar(100) DEFAULT NULL,
  `Category` varchar(10) DEFAULT NULL,
  `guardianRelation` varchar(20) DEFAULT NULL,
  `guardianContact` decimal(10,0) DEFAULT NULL,
  `occupation` varchar(40) DEFAULT NULL,
  `localAddress` varchar(200) DEFAULT NULL,
  `localCity` varchar(100) DEFAULT NULL,
  `localDistrict` varchar(100) DEFAULT NULL,
  `localState` varchar(100) DEFAULT NULL,
  `localPIN` int(6) DEFAULT NULL,
  `permanentAddress` varchar(200) DEFAULT NULL,
  `permanentCity` varchar(100) DEFAULT NULL,
  `permanentDistrict` varchar(100) DEFAULT NULL,
  `imagePath` varchar(200) DEFAULT NULL,
  `permanentState` varchar(100) DEFAULT NULL,
  `permanentPIN` decimal(6,0) DEFAULT NULL,
  `fatherName` varchar(100) DEFAULT NULL,
  `fatherContact` decimal(10,0) DEFAULT NULL,
  `fatherOccupation` varchar(100) DEFAULT NULL,
  `fatherEducation` varchar(50) DEFAULT NULL,
  `motherName` varchar(100) DEFAULT NULL,
  `motherContact` decimal(10,0) DEFAULT NULL,
  `motherOccupation` varchar(100) DEFAULT NULL,
  `motherEducation` varchar(100) DEFAULT NULL,
  `preSchool` varchar(100) DEFAULT NULL,
  `preSchAddress` varchar(150) DEFAULT NULL,
  `preSchoolContact` decimal(10,0) DEFAULT NULL,
  `lastExam` varchar(20) DEFAULT NULL,
  `percentage` double(5,2) DEFAULT NULL,
  `board` varchar(20) DEFAULT NULL,
  `schoolWebsite` varchar(50) DEFAULT NULL,
  `preRemarks` varchar(30) DEFAULT NULL,
  `examYear` date DEFAULT NULL,
  `photo` blob,
  `class` varchar(20) DEFAULT NULL,
  `section` varchar(20) DEFAULT NULL,
  `busRoute` varchar(100) DEFAULT NULL,
  `fee` double(5,2) DEFAULT NULL,
  `isEnablePreSchInfo` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `branchId` (`branchId`),
  CONSTRAINT `SDM_CONS` FOREIGN KEY (`branchId`) REFERENCES `schoolbranch` (`branchId`)
);

CREATE TABLE `generalsettings` (
  `id` int(4) NOT NULL AUTO_INCREMENT,
  `propertyName` varchar(150) NOT NULL,
  `propertyValue` varchar(150) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `schoolbranch` (
  `branchId` int(4) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `address` varchar(200) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `stateId` int(4) DEFAULT NULL,
  `districtId` int(4) DEFAULT NULL,
  `isMainBranch` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`branchId`)
);